services:
  api:
    build: .
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: requirements.txt
    environment:
      - DATABASE_URL=sqlite:///data/sql_app.db
    volumes:
      - .:/app
      - sqlite_data:/app/data
    restart: unless-stopped

volumes:
  sqlite_data:
